version: "2"
services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=standup
      - POSTGRES_PASSWORD=standup
    ports:
      - "5432:5432"

  slackbot:
    build: .
    env_file: .env
    depends_on:
      - database
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
