version: 2
jobs:
  test:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: ./node_modules/.bin/codecov
  deploy:
    docker:
      - image: 18fgsa/cloud-foundry-cli
    steps:
      - checkout
      - deploy:
          name: cf push
          command: cf_deploy.sh $CF_APP $CF_ORG $CF_SPACE
workflows:
  version: 2
  build:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - develop
